### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by mikaeleythor** [mikaeleythor/itu-minitwit-ops#13]
**Describe Feature**
While keeping Dev and Ops on separate branches in the same repo is an anti pattern, it makes CI/CD easy.

**Additional context**
- [Dev repo](https://github.com/Akongstad/DevOps-group-p/)
- [Ops repo](https://github.com/mikaeleythor/itu-minitwit-ops/)

**Task list**
- [x] Set up cronjob in Dev repo to make a release once per week (also push updated images **with descriptive tags**).
- [ ] Set up automatic tests in Ops repo
- [ ] Set up cronjob in Ops repo to make a release once per week (also apply all manifests)
