### ISSUE TITLE
Implement NGINX Ingress

### ISSUE THREAD

**Issue by mikaeleythor** [mikaeleythor/itu-minitwit-ops#6]
**Context**
Expose backend and frontend microservices to the internet.

*Make sure to have Prometheus configs in mind, example [here](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/)*

**Subtasks**
- [x] Write a testing script for the LoadBalancer / minitwit_simulator.py
- [x] Refactor reverse proxy configs for Ingress
- [x] Provision a development cluster with a load-balancer
- [x] Install NGINX Ingress Controller
- [x] TEST + DEBUG

**Expected results**
Requests to our domain will be routed according to path to relevant microservices. Stage is set for setting up routing for metrics and logging.
Stage is set for exposing NGINX metrics.

**Comment by mikaeleythor** [comment]
See [ingress-nginx docs](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#rewrite)
